# Generated by Django 2.2.7 on 2019-12-06 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cervicedesk', '0002_qrcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='unigue_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cervicedesk.QRZone'),
        ),
    ]
