# Generated by Django 2.2.7 on 2019-12-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervicedesk', '0003_auto_20191206_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
