# Generated by Django 2.2.7 on 2019-12-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cervicedesk', '0004_qrcode_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='unigue_id',
            new_name='unique_id',
        ),
    ]
