# Generated by Django 2.2.7 on 2019-12-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervicedesk', '0005_auto_20191206_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'In work'), (3, 'Complete')], default=1),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qrzone',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
